# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1453295803);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.cache.memory.enable", false);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "FR");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151216205749");
user_pref("browser.slowStartup.averageTime", 15208);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20151216205749");
user_pref("browser.startup.homepage_override.mstone", "38.5.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1453382082639");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1453295745318");
user_pref("datareporting.policy.firstRunTime", "1453295682638");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 14514);
user_pref("datareporting.sessions.current.main", 9901);
user_pref("datareporting.sessions.current.sessionRestored", 14863);
user_pref("datareporting.sessions.current.startTime", "1453295897792");
user_pref("datareporting.sessions.current.totalTime", 34);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1453295648294,\"a\":26,\"t\":181,\"c\":true,\"m\":26471,\"fp\":36220,\"sr\":36981}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1453295842087,\"a\":8,\"t\":42,\"c\":true,\"m\":111,\"fp\":4257,\"sr\":4379}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1453295887671,\"a\":1,\"t\":7,\"c\":true,\"m\":111,\"fp\":-1,\"sr\":-1}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.5.0");
user_pref("extensions.lastAppVersion", "38.5.0");
user_pref("extensions.lastPlatformVersion", "38.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.5.0\",\"st\":1453288347000,\"mt\":1450302411000}}}");
user_pref("gecko.buildID", "20151216205749");
user_pref("gecko.mstone", "38.5.0");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1453295746);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20151216205749");
user_pref("media.gmp-manager.lastCheck", 1453295745);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.use-cache", false);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 49236);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1453295907);
user_pref("toolkit.telemetry.previousBuildID", "20151216205749");
