#!/bin/sh
### BEGIN INIT INFO
# Provides:          xvfb
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the FrameBuffer X
# Description:       Start the FrameBuffer X with user specific in
#                    /etc/default/xvfb
### END INIT INFO


DESC="Framebuffer X"
DAEMON="/usr/bin/Xvfb"
PIDFILE="/var/run/xvfb.pid"
PKGNAME=xvfb
SCRIPTNAME=/etc/init.d/${PKGNAME}


# Include the default user configuration if exists
[ -r /etc/default/${PKGNAME} ] && . /etc/default/${PKGNAME}

DAEMON_ARGS="${X_SERVER_NUMBER} -nolisten tcp -fbdir ${FBDIR}" 

# Exit if java is not executable or Selenium jar is not readable
[ -x "${DAEMON}" ] || exit 0

# Load the VERBOSE setting and other rcS variables
[ -f /etc/default/rcS ] && . /etc/default/rcS

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

if [ -z "${RUN_AT_STARTUP}" -o "${RUN_AT_STARTUP}" != "YES" ]; then
    log_warning_msg "Not starting $PKGNAME, edit /etc/default/$PKGNAME to start it."
    exit 0
fi

do_start()
{
    start-stop-daemon --start --background --quiet --pidfile ${PIDFILE} --exec ${DAEMON} --test
    [ "$?" = "0" ] || return 1
    start-stop-daemon --start --background --quiet --pidfile ${PIDFILE} --make-pidfile --exec ${DAEMON} -- ${DAEMON_ARGS}
    [ "$?" = "0" ] || return 2
    return 0
}

do_stop()
{
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile ${PIDFILE}
    [ "$?" = "2" ] && return 2
    rm -rf ${PIDFILE}
    [ "$?" = 0 ] && return 0 || return 1
}

case "$1" in 
    start) 
        [ "${VERBOSE}" != "no" ] && log_daemon_msg "Starting ${DESC}" "${PKGNAME}"
        do_start
        case "$?" in
            0|1) [ "${VERBOSE}" != "no" ] && log_end_msg 0 ;;
            2) [ "${VERBOSE}" != "no" ] && log_end_msg 1 ;;
        esac
        ;;
    stop) 
        [ "${VERBOSE}" != no ] && log_daemon_msg "Stopping ${DESC}" "${PKGNAME}"
        do_stop
        case "$?" in
            0|1) [ "${VERBOSE}" != no ] && log_end_msg 0 ;;
            2) [ "${VERBOSE}" != no ] && log_end_msg 1 ;;
        esac
        ;;
    status)
        status_of_proc ${DAEMON} ${PKGNAME} -p ${PIDFILE}
         ;;
    restart) 
        [ "${VERBOSE}" != no ] && log_daemon_msg "Stopping ${DESC}" "${PKGNAME}"
        do_stop
        case "$?" in
            0|1)
                do_start
                case "$?" in
                    0) log_end_msg 0 ;;
                    1) log_end_msg 1 ;;
                    *) log_end_msg 1 ;;
                esac
                ;;
            *) log_end_msg 1 ;;
        esac
        ;;
    *) 
        echo "Usage: ${SCRIPTNAME} {start|stop|restart}" 
        exit 3
esac 
