#!/bin/bash 
# 
# /etc/rc.d/init.d/xvfb 
# 
# Author: Brian Connolly (LabKey.org) 
# 
# chkconfig: 345 98 90 
# description: Starts Virtual Framebuffer process to enable the  
# LabKey server to use R. 
# 
# 

# Include the default user configuration if exists
[ -r /etc/default/xvfb ] && . /etc/default/xvfb

XVFB_OUTPUT=/tmp/Xvfb.out 
PIDFILE=/var/run/xvfb.pid

XVFB=/usr/bin/Xvfb 
XVFB_OPTIONS="${X_SERVER_NUMBER} -nolisten tcp -fbdir ${FBDIR}" 


# Source function library. 
. /etc/init.d/functions 

start() { 
    echo -n "Starting : X Virtual Frame Buffer " 
    $XVFB $XVFB_OPTIONS >>$XVFB_OUTPUT 2>&1& 
    PID=$!
    RETVAL=$? 
    echo ${PID} > ${PIDFILE}
    echo 
    return $RETVAL 
} 

stop() { 
    echo -n "Shutting down : X Virtual Frame Buffer" 
    PID=`cat ${PIDFILE}`
    kill -TERM ${PID} &>/dev/null
    rm -f ${PIDFILE}
    echo 
    return 0 
} 

status() {
    if [ ! -e ${PIDFILE} ]; then
        echo "Xvfb is not running"
        return 1
    fi
    PID=`cat ${PIDFILE}`
    PIDRUN=`ps -eaf | awk '{ print $2 }' | grep "^${PID}$"`
    if [ -z "${PIDRUN}" ]; then
        echo "Xvfb is not running"
        return 1
    fi
    echo "Xvfb is running"
}


case "$1" in 
  start) 
    start 
    ;; 
  stop) 
    stop 
    ;; 
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *) 
    echo "Usage: xvfb {start|stop}" 
    exit 1 
    ;; 
esac 
exit $?
