#!/bin/bash 
# 
# /etc/rc.d/init.d/xvfb 
# 
# Author: Brian Connolly (LabKey.org) 
# 
# chkconfig: 345 98 90 
# description: Starts Virtual Framebuffer process to enable the  
# LabKey server to use R. 
# 
# 

# X number
X_SERVER_NUMBER=":99"
# Directory for files containing memory mapping
FBDIR=/var/run

XVFB_OUTPUT=/tmp/Xvfb.out 

XVFB=/usr/bin/Xvfb 
XVFB_OPTIONS="${X_SERVER_NUMBER} -nolisten tcp -fbdir ${FBDIR}" 


# Source function library. 
. /etc/init.d/functions 

start() { 
    echo -n "Starting : X Virtual Frame Buffer " 
    $XVFB $XVFB_OPTIONS >>$XVFB_OUTPUT 2>&1& 
    RETVAL=$? 
    echo 
    return $RETVAL 
} 

stop() { 
    echo -n "Shutting down : X Virtual Frame Buffer" 
    echo 
    killproc Xvfb 
    echo 
    return 0 
} 



case "$1" in 
  start) 
    start 
    ;; 
  stop) 
    stop 
    ;; 
  *) 
    echo "Usage: xvfb {start|stop}" 
    exit 1 
    ;; 
esac 
exit $?
